name: Publish to Lit

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Luvit
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh
          sudo mv lit /usr/local/bin/
          sudo mv luvi /usr/local/bin/
          sudo mv luvit /usr/local/bin/

      - name: Setup Lit Private Key
        run: |
          mkdir -p ~/.ssh
          echo "$LIT_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          LIT_PRIVATE_KEY: ${{ secrets.LIT_PRIVATE_KEY }}

      - name: Authenticate Lit
        run: |
          lit auth Richy-Z
        # run: |
        #   lit auth ${{ secrets.LIT_USERNAME }}

      - name: Add and Publish to Lit
        run: |
          lit add .
          lit publish .
